version: "3.9"
services:
  mysql:
    image: mysql:5.7.39
    expose:
      - "3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  api:
    build: .
    ports:
      - "3030:8080"
    links:
      - "mysql:mysql"
    environment:
      - ENV=prod
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PWD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql

